apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

namespace: zahori

resources:
  - ../../base
  - ../../apps/consul/overlays/dev
  - ../../apps/postgresql/overlays/dev
  - ../../apps/zahori-server/overlays/dev
# namePrefix: dev-
