apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true
  labels:
    app: consul

commonLabels:
  app: consul

configMapGenerator:
  - name: consul-config
    files:
      - server.hcl
resources:
  - deployment.yaml
  - service.yaml
  - storage.yaml
