apiVersion: v1
items:
  - apiVersion: moon.aerokube.com/v1
    kind: BrowserSet
    metadata:
      annotations:
        meta.helm.sh/release-name: moon
        meta.helm.sh/release-namespace: moon
      generation: 1
      labels:
        app.kubernetes.io/managed-by: Helm
      name: default
      namespace: moon
    spec:
      cypress:
        chrome:
          repository: quay.io/browsers/cypress-chrome
        chromium:
          repository: quay.io/browsers/cypress-chromium
        edge:
          repository: quay.io/browsers/cypress-edge
        electron:
          repository: quay.io/browsers/cypress-electron
        firefox:
          repository: quay.io/browsers/cypress-firefox
      devtools:
        chrome:
          repository: quay.io/browser/devtools-google-chrome-stable
      playwright:
        chrome:
          repository: quay.io/browser/playwright-chrome
        chromium:
          repository: quay.io/browser/playwright-chromium
        firefox:
          repository: quay.io/browser/playwright-firefox
        webkit:
          repository: quay.io/browser/playwright-webkit
      selenium:
        MicrosoftEdge:
          default: 110.0.1587.57-3
          repository: quay.io/browser/microsoft-edge-stable
        chrome:
          default: 110.0.5481.177-3
          repository: quay.io/browser/google-chrome-stable
        firefox:
          default: 110.0.1-3
          repository: quay.io/browser/firefox-mozilla-build
        opera:
          default: 96.0.4693.20-4
          repository: quay.io/browser/opera-stable
        safari:
          default: 15.0-0
          repository: quay.io/browser/safari
kind: List
metadata:
  resourceVersion: ""
