kind: PersistentVolume
apiVersion: v1
metadata:
  name: zahori-pv
  labels:
    app: zahori
    type: local
spec:
  storageClassName: null
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: zahori-pv-claim
  labels:
    app: zahori
spec:
  storageClassName: null
