apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: consul-ingressroute
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`consul.test`) && PathPrefix(`/`)
      kind: Rule
      services:
        - name: openzahori-consul-service
          port: 8500
